strict-sigcheck = false

[Messenger]
enabled = true
brand = "hush"
github-dlurl = "https://github.com/blkegl/Apk/releases/tag/messenger"
arch = "arm64-v8a"
#changelog-keywords = ["Messenger"]

[Messenger.patches]
"github:SysAdminDoc/HushMessenger" = { include = [] }

[Facebook]
enabled = true
brand = "hush"
github-dlurl = "https://github.com/blkegl/Apk/releases/tag/facebook"
arch = "arm64-v8a"

[Facebook.patches]
"github:SysAdminDoc/Hushfacebook" = { include = [] }
