strict-sigcheck = false

[Messenger]
enabled = true
brand = "hush"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/messenger/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/facebook-messenger-580-0-0-49-91-release/facebook-messenger-580-0-0-49-91-5-android-apk-download/"
#arch = "arm64-v8a"
#changelog-keywords = ["Messenger"]

[Messenger.patches]
"github:SysAdminDoc/HushMessenger" = { exclude = ["Install beside Meta apps"] }

[Facebook]
enabled = false
brand = "hush"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
arch = "arm64-v8a"

[Facebook.patches]
"github:SysAdminDoc/HushMessenger" = { exclude = ["Install beside Meta's apps"] }
